export type BatteryProduct = {
    id: string;
    brand: string;
    series?: string;
    sizeKwh: number;
    inverter: string;
    systemType: string;
    module: string;
    phase: number;
    price: number;
    rebate: number;
    notes?: string;
    tier: "value" | "medium" | "premium";
    image?: string;
};

type BatteryProductBase = Omit<BatteryProduct, "id">;

const batteryData: BatteryProductBase[] = [
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 9.6,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR096 (9.6 kWh)",
        phase: 1,
        price: 10970,
        rebate: 3168,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 12.8,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR128 (12.8 kWh)",
        phase: 1,
        price: 12600,
        rebate: 4224,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 16,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR160 (16 kWh)",
        phase: 1,
        price: 14650,
        rebate: 5280,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: 1,
        price: 16700,
        rebate: 6336,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: 1,
        price: 17750,
        rebate: 6336,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 9.6,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR096 (9.6 kWh)",
        phase: 3,
        price: 10970,
        rebate: 3168,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 12.8,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR128 (12.8 kWh)",
        phase: 3,
        price: 12600,
        rebate: 4224,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 16,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR160 (16 kWh)",
        phase: 3,
        price: 14650,
        rebate: 5280,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: 3,
        price: 16700,
        rebate: 6336,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: 3,
        price: 17750,
        rebate: 6336,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 25.6,
        inverter: "SH10RT",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBR256 (3.2 kWh)",
        phase: 3,
        price: 22740,
        rebate: 8448,
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 10,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH100 (10 kWH)",
        phase: 1,
        price: 11700,
        rebate: 3300,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH150 (15 kWH)",
        phase: 1,
        price: 14950,
        rebate: 4950,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH200 (20 kWH)",
        phase: 1,
        price: 18200,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH250 (25 kWH)",
        phase: 1,
        price: 22250,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH150 (15 kWH)",
        phase: 1,
        price: 16000,
        rebate: 4950,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH200 (20 kWH)",
        phase: 1,
        price: 19250,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH250 (25 kWH)",
        phase: 1,
        price: 23250,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 10,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 3p",
        module: "Sungrow SBH100 (10 kWH)",
        phase: 3,
        price: 11700,
        rebate: 3300,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 3p",
        module: "Sungrow SBH150 (15 kWH)",
        phase: 3,
        price: 14950,
        rebate: 4950,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 3p",
        module: "Sungrow SBH200 (20 kWH)",
        phase: 3,
        price: 18200,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 3p",
        module: "Sungrow SBH250 (25 kWH)",
        phase: 3,
        price: 22250,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBH150 (15 kWH)",
        phase: 3,
        price: 16000,
        rebate: 4950,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBH200 (20 kWH)",
        phase: 3,
        price: 19250,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBH250 (25 kWH)",
        phase: 3,
        price: 23250,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 3p",
        module: "Sungrow SBH200 (20 kWH)",
        phase: 3,
        price: 20500,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 3p",
        module: "Sungrow SBH250 (25 kWH)",
        phase: 3,
        price: 24550,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 30,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 3p",
        module: "Sungrow SBH300 (30 kWH)",
        phase: 3,
        price: 27850,
        rebate: 9900,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 35,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 3p",
        module: "Sungrow SBH350 (35 kWH)",
        phase: 3,
        price: 31150,
        rebate: 11550,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 40,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 3p",
        module: "Sungrow SBH400 (40 kWH)",
        phase: 3,
        price: 34550,
        rebate: 13200,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "GoodWe",
        sizeKwh: 9.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 9.6-H-20 (9.6 kWh)",
        phase: 1,
        price: 9090,
        rebate: 3168,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 12.8,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 12.8-H-20 (12.8 kWh)",
        phase: 1,
        price: 10300,
        rebate: 4224,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 16,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 16.0-H-20 (16.0 kWh)",
        phase: 1,
        price: 12000,
        rebate: 5280,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: 1,
        price: 14050,
        rebate: 6336,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW10KL-ET/GW9900-ET-20",
        systemType: "AC-coupled 10 kW - 3p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: 3,
        price: 15250,
        rebate: 6336,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 25.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 25.6-H-20 (25.6 kWh)",
        phase: 1,
        price: 18800,
        rebate: 8448,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 10,
        inverter: "Anker-X1-H5K-S(5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 1,
        price: 9900,
        rebate: 3300,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 15,
        inverter: "Anker-X1-H5K-S(5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 1,
        price: 12700,
        rebate: 4950,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 1,
        price: 16450,
        rebate: 6600,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 1,
        price: 19650,
        rebate: 8250,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 1,
        price: 22850,
        rebate: 9900,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 10,
        inverter: "Anker-X1-H5K-S(5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 9900,
        rebate: 3300,
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 15,
        inverter: "Anker-X1-H5K-S(5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 12700,
        rebate: 4950,
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 8 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 16450,
        rebate: 6600,
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 8 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 19650,
        rebate: 8250,
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-P6K-S(6KW 1P)",
        systemType: "AC-coupled 8 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 22850,
        rebate: 9900,
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 17500,
        rebate: 6600,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 20700,
        rebate: 8250,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 23800,
        rebate: 9900,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 45,
        inverter: "Anker-X1-H10K-T+12K-T",
        systemType: "AC-coupled 22 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: 3,
        price: 36400,
        rebate: 14850,
        notes: "10 & 12KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Tesla",
        sizeKwh: 13.5,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5kWh)",
        phase: 1,
        price: 15050,
        rebate: 4455,
        tier: "premium",
        image: "/Tesla/TeslaPowerwall.webp",
    },
    {
        brand: "Tesla",
        sizeKwh: 27,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5kWh)",
        phase: 1,
        price: 28700,
        rebate: 8910,
        tier: "premium",
        image: "/Tesla/TeslaPowerwall.webp",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 8.06,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 9350,
        rebate: 2660,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 14250,
        rebate: 5320,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 15650,
        rebate: 5320,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 24.18,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 21250,
        rebate: 7979,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 32.24,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 27500,
        rebate: 10639,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 40.3,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: 1,
        price: 33600,
        rebate: 13299,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 8.06,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 9350,
        rebate: 2660,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 14250,
        rebate: 5320,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 15650,
        rebate: 5320,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 24.18,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 21250,
        rebate: 7979,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 32.24,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 27500,
        rebate: 10639,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 40.3,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 3p",
        module: "SigenStor BAT 8.0",
        phase: 3,
        price: 33600,
        rebate: 13299,
        tier: "medium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 9.9,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti(B500)",
        phase: 1,
        price: 9200,
        rebate: 3267,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 14.85,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti(B500)",
        phase: 1,
        price: 11900,
        rebate: 4901,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 19.8,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti(B500)",
        phase: 1,
        price: 14900,
        rebate: 6534,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 24.75,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti(B500)",
        phase: 1,
        price: 17900,
        rebate: 8168,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
];

export const BatteryList: BatteryProduct[] = batteryData.map((item, index) => {
    const slug = item.module
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
    const sizePart = String(item.sizeKwh).replace(/\./g, "-");
    return {
        ...item,
        id: `${slug || "battery"}-${sizePart}-${index}`,
    };
});
