export type BatteryComboProduct = {
    brand: string;
    batterySeries?: string;
    batterySizeKwh: number;
    batteryModule: string;
    solarSizeKw: number;
    solarModule: string;
    inverter: string;
    phase: string;
    price: number;
    rebate: number;
    netPrice: number;
    notes?: string;
    tier: "value" | "medium" | "premium";
};

export const BatteryComboList: BatteryComboProduct[] = [
    // Sungrow SBR combos
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 9.6,
        batteryModule: "Sungrow SBR096 (9.6 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 14218,
        rebate: 3168,
        netPrice: 11100,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 12.8,
        batteryModule: "Sungrow SBR128 (12.8 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 15874,
        rebate: 4224,
        netPrice: 11700,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 16,
        batteryModule: "Sungrow SBR160 (16 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 18680,
        rebate: 5280,
        netPrice: 13400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 19.2,
        batteryModule: "Sungrow SBR192 (19.2 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 21736,
        rebate: 6336,
        netPrice: 15400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 25.6,
        batteryModule: "Sungrow SBR256 (3.2 kWh)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "SH10RT",
        phase: "3",
        price: 26848,
        rebate: 8448,
        netPrice: 18400,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBR",
        batterySizeKwh: 25.6,
        batteryModule: "Sungrow SBR256 (3.2 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SH10RT",
        phase: "3",
        price: 27548,
        rebate: 8448,
        netPrice: 19100,
        tier: "premium",
    },
    // Sungrow SBH combos
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 10,
        batteryModule: "Sungrow SBH100 (10 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 14950,
        rebate: 3300,
        netPrice: 11700,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 15,
        batteryModule: "Sungrow SBH150 (15 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 18950,
        rebate: 4950,
        netPrice: 14000,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 20,
        batteryModule: "Sungrow SBH200 (20 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SH5.0RS-ADA",
        phase: "1/3",
        price: 22200,
        rebate: 6600,
        netPrice: 15600,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 20,
        batteryModule: "Sungrow SBH200 (20 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SH10RS-ADA",
        phase: "1/3",
        price: 24100,
        rebate: 6600,
        netPrice: 17500,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 25,
        batteryModule: "Sungrow SBH250 (25 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SH10RS-ADA",
        phase: "1/3",
        price: 28050,
        rebate: 8250,
        netPrice: 19800,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 30,
        batteryModule: "Sungrow SBH300 (30 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SH10RT",
        phase: "3",
        price: 32050,
        rebate: 9900,
        netPrice: 22200,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 35,
        batteryModule: "Sungrow SBH350 (35 kWh)",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "SH15T",
        phase: "3",
        price: 37100,
        rebate: 11550,
        netPrice: 25600,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        batterySeries: "SBH",
        batterySizeKwh: 40,
        batteryModule: "Sungrow SBH400 (40 kWh)",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "SH15T",
        phase: "3",
        price: 40550,
        rebate: 13200,
        netPrice: 27400,
        tier: "premium",
    },
    // GoodWe combos
    {
        brand: "GoodWe",
        batterySizeKwh: 9.6,
        batteryModule: "LX F 9.6-H-20 (9.6 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "GW5K-EH/GW5000N-EH",
        phase: "1/3",
        price: 12340,
        rebate: 3168,
        netPrice: 9200,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 12.8,
        batteryModule: "LX F 12.8-H-20 (12.8 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "GW5K-EH/GW5000N-EH",
        phase: "1/3",
        price: 13550,
        rebate: 4224,
        netPrice: 9400,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 16,
        batteryModule: "LX F 16.0-H-20 (16.0 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "GW5K-EH/GW5000N-EH",
        phase: "1/3",
        price: 16000,
        rebate: 5280,
        netPrice: 10800,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 19.2,
        batteryModule: "LX F 19.2-H-20 (19.2 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "GW5K-EH/GW5000N-EH",
        phase: "1/3",
        price: 18050,
        rebate: 6336,
        netPrice: 11800,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 19.2,
        batteryModule: "LX F 19.2-H-20 (19.2 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "GW10KL-ET/GW9900-ET-20",
        phase: "3",
        price: 19250,
        rebate: 6336,
        netPrice: 13000,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 25.6,
        batteryModule: "LX F 19.2-H-20 (19.2 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "GW10KL-ET/GW9900-ET-20",
        phase: "3",
        price: 22550,
        rebate: 8448,
        netPrice: 14200,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 25.6,
        batteryModule: "LX F 25.6-H-20 (25.6 kWh)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "GW10KL-ET/GW9900-ET-20",
        phase: "3",
        price: 22650,
        rebate: 8448,
        netPrice: 14300,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 25.6,
        batteryModule: "LX F 25.6-H-20 (25.6 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "GW10KL-ET/GW9900-ET-20",
        phase: "3",
        price: 23300,
        rebate: 8448,
        netPrice: 14900,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    {
        brand: "GoodWe",
        batterySizeKwh: 25.6,
        batteryModule: "LX F 25.6-H-20 (25.6 kWh)",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "GW10KL-ET/GW9900-ET-20",
        phase: "3",
        price: 24550,
        rebate: 8448,
        netPrice: 16200,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    // Bluetti combos
    {
        brand: "Bluetti",
        batterySizeKwh: 9.9,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 12450,
        rebate: 3267,
        netPrice: 9200,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 9.9,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 13200,
        rebate: 3267,
        netPrice: 10000,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 9.9,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 13350,
        rebate: 3267,
        netPrice: 10100,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 9.9,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 14000,
        rebate: 3267,
        netPrice: 10800,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 14.85,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 15150,
        rebate: 4901,
        netPrice: 10300,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 14.85,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 15900,
        rebate: 4901,
        netPrice: 11000,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 14.85,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 16050,
        rebate: 4901,
        netPrice: 11200,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 14.85,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 16700,
        rebate: 4901,
        netPrice: 11800,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 19.8,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 18950,
        rebate: 6534,
        netPrice: 12500,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 19.8,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 19050,
        rebate: 6534,
        netPrice: 12600,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 19.8,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 19700,
        rebate: 6534,
        netPrice: 13200,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 24.75,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 21900,
        rebate: 8168,
        netPrice: 13800,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 24.75,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 22050,
        rebate: 8168,
        netPrice: 13900,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 24.75,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 22700,
        rebate: 8168,
        netPrice: 14600,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 29.7,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 24650,
        rebate: 9801,
        netPrice: 14900,
        tier: "value",
    },
    {
        brand: "Bluetti",
        batterySizeKwh: 29.7,
        batteryModule: "Bluetti (B500)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "EP760",
        phase: "1",
        price: 25300,
        rebate: 9801,
        netPrice: 15500,
        tier: "value",
    },
    // Anker Solix combos
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 10,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "AC-coupled 5 kW - 1p",
        phase: "1/3",
        price: 13150,
        rebate: 3300,
        netPrice: 9900,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 15,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "AC-coupled 5 kW - 1p",
        phase: "1/3",
        price: 15950,
        rebate: 4950,
        netPrice: 11000,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 20,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 20450,
        rebate: 6600,
        netPrice: 13900,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 25,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 23650,
        rebate: 8250,
        netPrice: 15400,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 30,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 26850,
        rebate: 9900,
        netPrice: 17000,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 20,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 20500,
        rebate: 6600,
        netPrice: 13900,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 25,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 23700,
        rebate: 8250,
        netPrice: 15500,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 30,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "AC-coupled 6 kW - 1p",
        phase: "1/3",
        price: 26900,
        rebate: 9900,
        netPrice: 17000,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 20,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 13.2,
        solarModule: "JKM510N",
        inverter: "AC-coupled 10 kW - 3p",
        phase: "3",
        price: 22300,
        rebate: 6600,
        netPrice: 15700,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 25,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 13.2,
        solarModule: "JKM510N",
        inverter: "AC-coupled 10 kW - 3p",
        phase: "3",
        price: 25500,
        rebate: 8250,
        netPrice: 17300,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 30,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 13.2,
        solarModule: "JKM510N",
        inverter: "AC-coupled 10 kW - 3p",
        phase: "3",
        price: 28600,
        rebate: 9900,
        netPrice: 18700,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        batterySeries: "Solix",
        batterySizeKwh: 45,
        batteryModule: "Anker-X1-B5-H",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "AC-coupled 22 kW - 3p",
        phase: "3",
        price: 42350,
        rebate: 14850,
        netPrice: 27500,
        notes: "10 & 12KW Has Only 3 Phase Available",
        tier: "medium",
    },
    // Tesla combos
    {
        brand: "Tesla",
        batterySizeKwh: 13.5,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 18300,
        rebate: 4455,
        netPrice: 13800,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 13.5,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 19050,
        rebate: 4455,
        netPrice: 14600,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 13.5,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 19200,
        rebate: 4455,
        netPrice: 14700,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 13.5,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 19850,
        rebate: 4455,
        netPrice: 15400,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 13.5,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 21050,
        rebate: 4455,
        netPrice: 16600,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 27,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 32850,
        rebate: 8910,
        netPrice: 23900,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 27,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 33500,
        rebate: 8910,
        netPrice: 24600,
        tier: "premium",
    },
    {
        brand: "Tesla",
        batterySizeKwh: 27,
        batteryModule: "Powerwall 3 (13.5 kWh)",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        phase: "1",
        price: 34700,
        rebate: 8910,
        netPrice: 25800,
        tier: "premium",
    },
    // Sigenenergy combos
    {
        brand: "Sigenenergy",
        batterySizeKwh: 16.12,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 6.51,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 5.0 SP",
        phase: "1/3",
        price: 17650,
        rebate: 5320,
        netPrice: 12400,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 16.12,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 5.0 SP",
        phase: "1/3",
        price: 18450,
        rebate: 5320,
        netPrice: 13200,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 16.12,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 20050,
        rebate: 5320,
        netPrice: 14800,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 16.12,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 20750,
        rebate: 5320,
        netPrice: 15500,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 24.18,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 9.765,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 25450,
        rebate: 7979,
        netPrice: 17500,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 24.18,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 25650,
        rebate: 7979,
        netPrice: 17700,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 24.18,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 26350,
        rebate: 7979,
        netPrice: 18400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 24.18,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 27650,
        rebate: 7979,
        netPrice: 19700,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 32.24,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 31900,
        rebate: 10639,
        netPrice: 21300,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 32.24,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 32600,
        rebate: 10639,
        netPrice: 22000,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 32.24,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 33900,
        rebate: 10639,
        netPrice: 23300,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 40.3,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 10.23,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 38000,
        rebate: 13299,
        netPrice: 24800,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 40.3,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 13.02,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 38700,
        rebate: 13299,
        netPrice: 25500,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        batterySizeKwh: 40.3,
        batteryModule: "SigenStor BAT 8.0",
        solarSizeKw: 14.88,
        solarModule: "JKM510N",
        inverter: "SigenStor EC 10.0 SP",
        phase: "1/3",
        price: 40000,
        rebate: 13299,
        netPrice: 26800,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
*** End Patch
