export type BatteryProduct = {
    id: string;
    brand: string;
    series?: string;
    sizeKwh: number;
    inverter: string;
    systemType: string;
    module: string;
    phase: string;
    price: number;
    rebate: number;
    notes?: string;
    tier: "value" | "medium" | "premium";
    image?: string;
};

type BatteryProductBase = Omit<BatteryProduct, "id">;

const batteryData: BatteryProductBase[] = [
    // Sungrow SBR modules
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 9.6,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR096 (9.6 kWh)",
        phase: "1/3",
        price: 12067,
        rebate: 3168,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 12.8,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR128 (12.8 kWh)",
        phase: "1/3",
        price: 13860,
        rebate: 4224,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 16,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR160 (16 kWh)",
        phase: "1/3",
        price: 16115,
        rebate: 5280,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: "1/3",
        price: 18370,
        rebate: 6336,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: "1/3",
        price: 19525,
        rebate: 6336,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 25.6,
        inverter: "SH10RT",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBR256 (3.2 kWh)",
        phase: "3",
        price: 25014,
        rebate: 8448,
        notes: "Best Price Product Of Three Phase Battery",
        tier: "premium",
        image: "/Sungrow/SungrowSBR.png",
    },
    // Sungrow SBH modules
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 10,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH100 (10 kWh)",
        phase: "1/3",
        price: 12870,
        rebate: 3300,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH150 (15 kWh)",
        phase: "1/3",
        price: 16445,
        rebate: 4950,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "1/3",
        price: 20020,
        rebate: 6600,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "1/3",
        price: 24475,
        rebate: 8250,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH150 (15 kWh)",
        phase: "1/3",
        price: 17600,
        rebate: 4950,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "1/3",
        price: 21175,
        rebate: 6600,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "1/3",
        price: 25575,
        rebate: 8250,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "3",
        price: 22550,
        rebate: 6600,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "3",
        price: 27005,
        rebate: 8250,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 30,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH300 (30 kWh)",
        phase: "3",
        price: 30635,
        rebate: 9900,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 35,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH350 (35 kWh)",
        phase: "3",
        price: 34265,
        rebate: 11550,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 40,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH400 (40 kWh)",
        phase: "3",
        price: 38005,
        rebate: 13200,
        tier: "premium",
        image: "/Sungrow/SungrowsSBH.webp",
    },
    // GoodWe batteries
    {
        brand: "GoodWe",
        sizeKwh: 9.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 9.6-H-20 (9.6 kWh)",
        phase: "1/3",
        price: 9999,
        rebate: 3168,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 12.8,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 12.8-H-20 (12.8 kWh)",
        phase: "1/3",
        price: 11330,
        rebate: 4224,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 16,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 16.0-H-20 (16.0 kWh)",
        phase: "1/3",
        price: 13200,
        rebate: 5280,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: "1/3",
        price: 15455,
        rebate: 6336,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW10KL-ET/GW9900-ET-20",
        systemType: "AC-coupled 10 kW - 3p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: "3",
        price: 16775,
        rebate: 6336,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 25.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 25.6-H-20 (25.6 kWh)",
        phase: "1/3",
        price: 20680,
        rebate: 8448,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    {
        brand: "GoodWe",
        sizeKwh: 25.6,
        inverter: "GW10KL-ET/GW9900-ET-20",
        systemType: "AC-coupled 10 kW - 3p",
        module: "LX F 25.6-H-20 (25.6 kWh)",
        phase: "3",
        price: 20405,
        rebate: 8448,
        notes: "10KW-Only 3-Phase Available, Best Price Product Of Three Phase Battery",
        tier: "value",
        image: "/GoodWe/goodwe-lynxf_usversion-33.jpg",
    },
    // Bluetti batteries
    {
        brand: "Bluetti",
        sizeKwh: 9.9,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 10120,
        rebate: 3267,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 14.85,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 13090,
        rebate: 4901,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 19.8,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 16390,
        rebate: 6534,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 24.75,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 19690,
        rebate: 8168,
        notes: "Best Price Product Of Single Phase Battery",
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    {
        brand: "Bluetti",
        sizeKwh: 29.7,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 22550,
        rebate: 9801,
        tier: "value",
        image: "/Bluetti/bluetti-ep600.jpg",
    },
    // Anker Solix batteries
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 10,
        inverter: "Anker-X1-H5K-S (5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 10890,
        rebate: 3300,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 15,
        inverter: "Anker-X1-H5K-S (5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 13970,
        rebate: 4950,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 18095,
        rebate: 6600,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 21615,
        rebate: 8250,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 25135,
        rebate: 9900,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 19250,
        rebate: 6600,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 22770,
        rebate: 8250,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 26180,
        rebate: 9900,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 45,
        inverter: "Anker-X1-H10K-T + 12K-T",
        systemType: "AC-coupled 22 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 40040,
        rebate: 14850,
        notes: "10 & 12KW Has Only 3 Phase Available",
        tier: "medium",
        image: "/Anker/Anker-SOLIX-X1-B5-H-5kWh.webp",
    },
    // Tesla batteries
    {
        brand: "Tesla",
        sizeKwh: 13.5,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5 kWh)",
        phase: "1",
        price: 16555,
        rebate: 4455,
        tier: "premium",
        image: "/Tesla/TeslaPowerwall.webp",
    },
    {
        brand: "Tesla",
        sizeKwh: 27,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5 kWh)",
        phase: "1",
        price: 31570,
        rebate: 8910,
        tier: "premium",
        image: "/Tesla/TeslaPowerwall.webp",
    },
    // Sigenenergy batteries
    {
        brand: "Sigenenergy",
        sizeKwh: 8.06,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 10285,
        rebate: 2660,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 15675,
        rebate: 5320,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 17215,
        rebate: 5320,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 24.18,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 23375,
        rebate: 7979,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 32.24,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 30250,
        rebate: 10639,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 40.3,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 36960,
        rebate: 13299,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
        image: "/Sigen/SigenStor-BAT8.jpeg",
    },
];

export const BatteryList: BatteryProduct[] = batteryData.map((item, index) => {
    const slug = item.module
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
    const sizePart = String(item.sizeKwh).replace(/\./g, "-");
    return {
        ...item,
        id: `${slug || "battery"}-${sizePart}-${index}`,
    };
});
