export type BatteryProduct = {
    brand: string;
    series?: string;
    sizeKwh: number;
    inverter: string;
    systemType: string;
    module: string;
    phase: string;
    price: number;
    rebate: number;
    netPrice: number;
    notes?: string;
    tier: "value" | "medium" | "premium";
};

export const BatteryList: BatteryProduct[] = [
    // Sungrow SBR modules
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 9.6,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR096 (9.6 kWh)",
        phase: "1/3",
        price: 10970,
        rebate: 3168,
        netPrice: 7800,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 12.8,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR128 (12.8 kWh)",
        phase: "1/3",
        price: 12600,
        rebate: 4224,
        netPrice: 8400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 16,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR160 (16 kWh)",
        phase: "1/3",
        price: 14650,
        rebate: 5280,
        netPrice: 9400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: "1/3",
        price: 16700,
        rebate: 6336,
        netPrice: 10400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 19.2,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBR192 (19.2 kWh)",
        phase: "1/3",
        price: 17750,
        rebate: 6336,
        netPrice: 11400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBR",
        sizeKwh: 25.6,
        inverter: "SH10RT",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Sungrow SBR256 (3.2 kWh)",
        phase: "3",
        price: 22740,
        rebate: 8448,
        netPrice: 14300,
        notes: "Best Price Product Of Three Phase Battery",
        tier: "premium",
    },
    // Sungrow SBH modules
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 10,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH100 (10 kWh)",
        phase: "1/3",
        price: 11700,
        rebate: 3300,
        netPrice: 8400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH150 (15 kWh)",
        phase: "1/3",
        price: 14950,
        rebate: 4950,
        netPrice: 10000,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "1/3",
        price: 18200,
        rebate: 6600,
        netPrice: 11600,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH5.0RS-ADA",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "1/3",
        price: 22250,
        rebate: 8250,
        netPrice: 14000,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 15,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH150 (15 kWh)",
        phase: "1/3",
        price: 16000,
        rebate: 4950,
        netPrice: 11100,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "1/3",
        price: 19250,
        rebate: 6600,
        netPrice: 12700,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH10RS-ADA",
        systemType: "AC-coupled 10 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "1/3",
        price: 23250,
        rebate: 8250,
        netPrice: 15000,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 20,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH200 (20 kWh)",
        phase: "3",
        price: 20500,
        rebate: 6600,
        netPrice: 13900,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 25,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH250 (25 kWh)",
        phase: "3",
        price: 24550,
        rebate: 8250,
        netPrice: 16300,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 30,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH300 (30 kWh)",
        phase: "3",
        price: 27850,
        rebate: 9900,
        netPrice: 18000,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 35,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH350 (35 kWh)",
        phase: "3",
        price: 31150,
        rebate: 11550,
        netPrice: 19600,
        tier: "premium",
    },
    {
        brand: "Sungrow",
        series: "SBH",
        sizeKwh: 40,
        inverter: "SH15T",
        systemType: "AC-coupled 15 kW - 1p",
        module: "Sungrow SBH400 (40 kWh)",
        phase: "3",
        price: 34550,
        rebate: 13200,
        netPrice: 21400,
        tier: "premium",
    },
    // GoodWe batteries
    {
        brand: "GoodWe",
        sizeKwh: 9.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 9.6-H-20 (9.6 kWh)",
        phase: "1/3",
        price: 9090,
        rebate: 3168,
        netPrice: 5900,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 12.8,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 12.8-H-20 (12.8 kWh)",
        phase: "1/3",
        price: 10300,
        rebate: 4224,
        netPrice: 6100,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 16,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 16.0-H-20 (16.0 kWh)",
        phase: "1/3",
        price: 12000,
        rebate: 5280,
        netPrice: 6700,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: "1/3",
        price: 14050,
        rebate: 6336,
        netPrice: 7700,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 19.2,
        inverter: "GW10KL-ET/GW9900-ET-20",
        systemType: "AC-coupled 10 kW - 3p",
        module: "LX F 19.2-H-20 (19.2 kWh)",
        phase: "3",
        price: 15250,
        rebate: 6336,
        netPrice: 8900,
        notes: "10KW-Only 3-Phase Available",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 25.6,
        inverter: "GW5K-EH/GW5000N-EH",
        systemType: "AC-coupled 5 kW - 1p",
        module: "LX F 25.6-H-20 (25.6 kWh)",
        phase: "1/3",
        price: 18800,
        rebate: 8448,
        netPrice: 10400,
        notes: "Upgrade to 3p: +$1000",
        tier: "value",
    },
    {
        brand: "GoodWe",
        sizeKwh: 25.6,
        inverter: "GW10KL-ET/GW9900-ET-20",
        systemType: "AC-coupled 10 kW - 3p",
        module: "LX F 25.6-H-20 (25.6 kWh)",
        phase: "3",
        price: 18550,
        rebate: 8448,
        netPrice: 10100,
        notes: "10KW-Only 3-Phase Available, Best Price Product Of Three Phase Battery",
        tier: "value",
    },
    // Bluetti batteries
    {
        brand: "Bluetti",
        sizeKwh: 9.9,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 9200,
        rebate: 3267,
        netPrice: 6000,
        tier: "value",
    },
    {
        brand: "Bluetti",
        sizeKwh: 14.85,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 11900,
        rebate: 4901,
        netPrice: 7000,
        tier: "value",
    },
    {
        brand: "Bluetti",
        sizeKwh: 19.8,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 14900,
        rebate: 6534,
        netPrice: 8400,
        tier: "value",
    },
    {
        brand: "Bluetti",
        sizeKwh: 24.75,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 17900,
        rebate: 8168,
        netPrice: 9800,
        notes: "Best Price Product Of Single Phase Battery",
        tier: "value",
    },
    {
        brand: "Bluetti",
        sizeKwh: 29.7,
        inverter: "EP760",
        systemType: "AC-coupled 7.6 kW - 1p",
        module: "Bluetti (B500)",
        phase: "1",
        price: 20500,
        rebate: 9801,
        netPrice: 10700,
        tier: "value",
    },
    // Anker Solix batteries
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 10,
        inverter: "Anker-X1-H5K-S (5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 9900,
        rebate: 3300,
        netPrice: 6600,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 15,
        inverter: "Anker-X1-H5K-S (5KW 1P)",
        systemType: "AC-coupled 5 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 12700,
        rebate: 4950,
        netPrice: 7800,
        notes: "Upgrade to 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 16450,
        rebate: 6600,
        netPrice: 9900,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 19650,
        rebate: 8250,
        netPrice: 11400,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-P6K-S (6KW 1P)",
        systemType: "AC-coupled 6 kW - 1p",
        module: "Anker-X1-B5-H",
        phase: "1/3",
        price: 22850,
        rebate: 9900,
        netPrice: 13000,
        notes: "Upgrade to 8 KW 3p: +$1000",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 20,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 17500,
        rebate: 6600,
        netPrice: 10900,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 25,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 20700,
        rebate: 8250,
        netPrice: 12500,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 30,
        inverter: "Anker-X1-H10K-T",
        systemType: "AC-coupled 10 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 23800,
        rebate: 9900,
        netPrice: 13900,
        notes: "10 KW Has Only 3 Phase Available",
        tier: "medium",
    },
    {
        brand: "Anker",
        series: "Solix",
        sizeKwh: 45,
        inverter: "Anker-X1-H10K-T + 12K-T",
        systemType: "AC-coupled 22 kW - 3p",
        module: "Anker-X1-B5-H",
        phase: "3",
        price: 36400,
        rebate: 14850,
        netPrice: 21600,
        notes: "10 & 12KW Has Only 3 Phase Available",
        tier: "medium",
    },
    // Tesla batteries
    {
        brand: "Tesla",
        sizeKwh: 13.5,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5 kWh)",
        phase: "1",
        price: 15050,
        rebate: 4455,
        netPrice: 10600,
        tier: "premium",
    },
    {
        brand: "Tesla",
        sizeKwh: 27,
        inverter: "Tesla Power Wall 3 (11.04 kW)",
        systemType: "AC-coupled 11 kW - 1p",
        module: "Powerwall 3 (13.5 kWh)",
        phase: "1",
        price: 28700,
        rebate: 8910,
        netPrice: 19800,
        tier: "premium",
    },
    // Sigenenergy batteries
    {
        brand: "Sigenenergy",
        sizeKwh: 8.06,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 9350,
        rebate: 2660,
        netPrice: 6700,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 5.0 SP",
        systemType: "AC-coupled 5 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 14250,
        rebate: 5320,
        netPrice: 9000,
        notes: "Upgrade to 3p: +$2000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 16.12,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 15650,
        rebate: 5320,
        netPrice: 10400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 24.18,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 21250,
        rebate: 7979,
        netPrice: 13300,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 32.24,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 27500,
        rebate: 10639,
        netPrice: 16900,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
    {
        brand: "Sigenenergy",
        sizeKwh: 40.3,
        inverter: "SigenStor EC 10.0 SP",
        systemType: "AC-coupled 10 kW - 1p",
        module: "SigenStor BAT 8.0",
        phase: "1/3",
        price: 33600,
        rebate: 13299,
        netPrice: 20400,
        notes: "Upgrade to 3p: +$1000",
        tier: "premium",
    },
];
